using System.Collections;
using System.Collections.Generic;
using UnityEngine;

public class Projectile : MonoBehaviour
{
    public int damage = 10;
 
    void Start()
    {
        Destroy(gameObject, 3);
    }
    private void OnCollisionEnter(Collision collision)
    {
        if (collision.gameObject.CompareTag("Enemy"))
        {
            collision.gameObject.GetComponent<Enemy>().Hit(damage);

        }
        Destroy(gameObject);
        if (collision.gameObject.CompareTag("Target"))
        {
            collision.gameObject.GetComponent<Target>().Hit();
            
        }
        Destroy(gameObject);
    }
}
